# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Knowledge(BaseModel):
    knowledge_items: typing.List["KnowledgeItem"]
    related_items: typing.List[str]
    tags: typing.List[str]

class KnowledgeItem(BaseModel):
    id: typing.Optional[int] = None
    header: typing.Optional[str] = None
    content: typing.Optional[str] = None
    node: typing.Optional["Node"] = None

class Node(BaseModel):
    targert_id: typing.Optional[int] = None
    relationship: typing.Optional[types.RelationShip] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
