# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class RelationShip(str, Enum):
    PARENT = "PARENT"
    CHILD = "CHILD"

# #########################################################################
# Generated classes (3)
# #########################################################################

class Knowledge(BaseModel):
    knowledge_items: typing.List["KnowledgeItem"]
    related_items: typing.List[str]
    tags: typing.List[str]

class KnowledgeItem(BaseModel):
    id: int
    header: str
    content: str
    node: "Node"

class Node(BaseModel):
    targert_id: int
    relationship: RelationShip

# #########################################################################
# Generated type aliases (0)
# #########################################################################
