# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Knowledge": types.Knowledge,
    "stream_types.Knowledge": stream_types.Knowledge,

    "types.KnowledgeItem": types.KnowledgeItem,
    "stream_types.KnowledgeItem": stream_types.KnowledgeItem,

    "types.Node": types.Node,
    "stream_types.Node": stream_types.Node,


    "types.RelationShip": types.RelationShip,

}