// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package llm

import (
	"MemoFluxServer/api/llm"
)

type ControllerV1 struct{}

func NewV1() llm.ILlmV1 {
	return &ControllerV1{}
}
